### ISSUE TITLE
Please do not use `GITHUB_TOKEN`

### ISSUE THREAD

**Issue by peaceiris** [juliendargelos/rollup-application#1]
Check your GitHub Pages status, you find that GitHub Pages build event did not start.

- Please do not use `GITHUB_TOKEN`, use `ACTIONS_DEPLOY_KEY` or `PERSONAL_TOKEN` 
  - cf. https://github.com/peaceiris/actions-gh-pages/issues/9
- Please use the latest version of peaceiris/actions-gh-pages
  - [Releases · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/releases)

**Comment by juliendargelos** [comment]
Hi, thanks for opening this issue (and creating actions-gh-pages !)
This repository is a template so I disabled GitHub actions and pages on purpose, this is why the build process keeps failing:

<img width="648" alt="Capture d’écran 2019-10-09 à 14 12 21" src="https://user-images.githubusercontent.com/3743321/66480668-7a0eca00-ea9f-11e9-9338-4023cf56bb74.png">

Actually, the workflow does complete in a regular repository. I understand why I should not use `GITHUB_TOKEN`, but, since it was working, I did not pay attention.

I will change this soon :)

**Comment by peaceiris** [comment]
I got it. Thank you.
